# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: WebApp-CI-YAML.$(Date:yyyyMMdd).$(Rev:r)

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: "Doing a package restore"
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'


- task: DotNetCoreCLI@2
  displayName: "Building the web application"
  inputs:
    command: 'build'
    projects: '**/*.csproj'
