name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: publish
      run: dotnet publish -c Release -o publish
    - name: Creating artifact directories
      run: |
         mkdir buildartifacts
    - name: Archive Application
      run: |
        zip -qq -r buildartifacts/Application.zip publish
    - name: Upload Application to Build Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: appzip
        path: buildartifacts/Application.zip
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: appzip
